run_id: run_v5_reward_v4
episodes: 500
learning_rate: 0.001
gamma: 0.99
batch_size: 64
target_update_freq: 100
reward_type: "v4"

epsilon:
  start: 1.0
  min: 0.05
  decay: 0.995

model_save_path: policies/policy_v5_reward_v4.pkl
csv_save_path: experiments/results_5.csv
