run_id: run_v8_reward_v8
episodes: 700
learning_rate: 0.001
gamma: 0.99
batch_size: 64
target_update_freq: 100
reward_type: "v8"

epsilon:
  start: 1.0
  min: 0.01
  decay: 0.993

model_save_path: policies/policy_v8.pkl
csv_save_path: experiments/results_8.csv
